version: '3.11'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./models:/app/models
    environment:
      - ENVIRONMENT=test
    command: pytest api/test_api.py
