version: '3.11'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Monter uniquement les dossiers et fichiers nécessaires
      - ./api:/app/api   # Monter uniquement le dossier 'api' avec le code de l'application
      - ./models:/app/models  # Monter le dossier 'models' pour charger les modèles nécessaires
      - ./requirements.txt:/app/requirements.txt  # Monter le fichier requirements si nécessaire
    environment:
      - ENVIRONMENT=development
    command: uvicorn api.main:app --host 0.0.0.0 --port 80 --reload

