name: CI/CD Pipeline

on:
  push:
    branches:
      - main

workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Run Tests
        run: |
          docker-compose -f docker-compose.ci.yml up --build --exit-code-from app

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: <AZURE_REGISTRY>.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-azure-app'
          images: '<AZURE_REGISTRY>.azurecr.io/my-app:latest'



