name: CI/CD Pipeline with Build and Deploy

on:
  push:
    branches: '**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: write  # Permissions nécessaires pour les actions GitHub

jobs:
  # Job de test
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Tests
        run: |
          docker-compose -f docker-compose.ci.yml up --build --exit-code-from app

  # Job de construction et déploiement
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: 'production'
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Connexion à ACR
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: myappregistry1.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      # Étape 3 : Construction et Push de l'image Docker
      - name: Build and push container image to ACR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: myappregistry1.azurecr.io/my-app:latest
          file: ./Dockerfile

      # Étape 4 : Connexion à Azure pour déploiement
      - name: Log in to Azure using Service Principal
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Étape 5 : Déploiement de l'image Docker sur Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'P7-myapp-deploy'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_7b9242731562463b871033fdeaa5aa0b }}
          images: 'myappregistry1.azurecr.io/my-app:latest'

