name: CI/CD Pipeline

on:
  push:
    branches: '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Tests
        run: |
          docker-compose -f docker-compose.ci.yml up --build --exit-code-from app


#  deploy:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - name: Log in to Azure Container Registry
#        uses: azure/docker-login@v1
#        with:
#          login-server: myappregistry1.azurecr.io
#          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
#          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
#      - name: Build and push Docker image
#        run: |
#          docker-compose -f docker-compose.prod.yml build
#          docker-compose -f docker-compose.prod.yml push
#      - name: Deploy to Azure Web App
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: 'my-azure-app'
#          images: 'myappregistry1.azurecr.io/my-app:latest'


#  deploy:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Docker
#        uses: docker/setup-buildx-action@v2
#
#      - name: Install Docker Compose
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y docker-compose
#
#      - name: Log in to Azure Container Registry
#        uses: azure/docker-login@v1
#        with:
#          login-server: myappregistry1.azurecr.io
#          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
#          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
#
#      - name: Build and push Docker image
#        run: |
#          docker-compose -f docker-compose.prod.yml build
#          docker-compose -f docker-compose.prod.yml push
#
#      - name: Deploy to Azure Web App
#        uses: azure/webapps-deploy@v2
#        with:
#          app-name: 'my-azure-app'
#          images: 'myappregistry1.azurecr.io/my-app:latest'

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: myappregistry1.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml push

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-azure-app'
          images: 'myappregistry1.azurecr.io/my-app:latest'


