name: CI/CD Pipeline with Build and Deploy

on:
  push:
    branches: '**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: write  # Permissions nécessaires pour les actions GitHub

jobs:
  # Job de test
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Run Tests
        run: |
          docker-compose -f docker-compose.ci.yml up --build --exit-code-from app
        env:
          APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}

  # Job de construction et déploiement
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: test
    environment:
      name: 'production'
    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Connexion à Azure via Azure CLI
      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Étape 3 : Connexion au registre ACR
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: myappregistry1.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      # Étape 4 : Construction et Push de l'image Docker
      - name: Build and push container image to registry
        run: |
          docker build . -t myappregistry1.azurecr.io/my-app:${{ github.sha }}
          docker push myappregistry1.azurecr.io/my-app:${{ github.sha }}
        env:
          APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}

      # Étape 5 : Déploiement de l'image Docker sur Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'P7-myapp-deploy'
          images: 'myappregistry1.azurecr.io/my-app:${{ github.sha }}'
          slot-name: 'production'
        env:
          APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}

      # Étape 6 : Déconnexion d'Azure
      - name: Azure logout
        run: |
          az logout
